import React from 'react'

const Terms = () => {
    return (
        <div className="gpt3__header section__padding">
            <div className="gpt3__header-content">
                <h1 className="gradient__text">Términos y Condiciones de Uso</h1>
                <h4 className="subtitle__color_h3"> Fecha de la última actualización efectiva: 14 Mayo, 2023</h4>
                <p>POR FAVOR LEA ESTOS TÉRMINOS DE USO ("ACUERDO" O "TÉRMINOS DE USO") ANTES DE UTILIZAR LOS SERVICIOS OFRECIDOS POR __DOMINIO__. ESTE ACUERDO ESTABLECE LOS TÉRMINOS Y CONDICIONES LEGALMENTE VINCULANTES PARA SU USO DEL SITIO WEB __NOMBRE__ Y TODOS LOS SERVICIOS RELACIONADOS, INCLUYENDO, SIN LIMITACIÓN, CUALQUIER CARACTERÍSTICA, CONTENIDO, SITIOS WEB (INCLUYENDO __WWW_DOMINIO__) O APLICACIONES OFRECIDAS OCASIONALMENTE POR FOTO AI EN RELACIÓN CON ELLO (COLECTIVAMENTE "SERVICIO(S)"). AL UTILIZAR LOS SERVICIOS DE CUALQUIER MANERA, USTED ACEPTA ESTAR OBLIGADO POR ESTE ACUERDO.</p>
                
                <br/>
                <h3 className="subtitle__color_h4">Aceptación Términos de Uso</h3>
                <p>El Servicio se ofrece sujeto a la aceptación sin modificación de todos estos Términos de uso y todas las demás reglas, políticas y procedimientos operativos que pueden publicarse periódicamente en relación con los Servicios de __NOMBRE__. Además, algunos servicios ofrecidos a través del Servicio pueden estar sujetos a términos y condiciones adicionales promulgados por __NOMBRE__ de vez en cuando; su uso de dichos servicios está sujeto a esos términos y condiciones adicionales, que se incorporan a estos Términos de uso por esta referencia.</p>
                <p>__NOMBRE__ puede, a su exclusivo criterio, negarse a ofrecer el Servicio a cualquier persona o entidad y cambiar sus criterios de elegibilidad en cualquier momento. Esta disposición es nula donde lo prohíba la ley y el derecho a acceder al Servicio se revoca en dichas jurisdicciones.</p>

                <br/>
                <h3 className="subtitle__color_h4">Reglas y Conducta</h3>
                <p>Al usar el servicio __NOMBRE__, usted acepta que el Servicio está destinado únicamente al propósito de entrenar modelos de IA de usted y su negocio, u otras personas para las que haya obtenido un consentimiento explícito. Usted reconoce y acepta que al entrenar modelos de IA de otra gente, debe tener su permiso expreso para usar su información y datos, entrenar y generar un chatbot de ellos generadas por IA.</p>
                <p>Como condición de uso, usted se compromete a no utilizar el Servicio para ningún propósito que esté prohibido por los Términos de uso. A modo de ejemplo, y no como una limitación, no deberá (y no permitirá que ningún tercero lo haga) realizar ninguna acción (incluido el uso del Sitio, cualquier Activo o nuestros modelos o derivados de nuestros modelos) que: constituiría una violación de cualquier ley, regla o regulación aplicable; infrinja cualquier propiedad intelectual u otro derecho de cualquier otra persona o entidad; es amenazante, abusivo, acosador, difamatorio, calumnioso, engañoso, fraudulento, invasivo de la privacidad de otra persona, tortuoso, obsceno, ofensivo, que promueve la autolesión o profano; crea Activos que explotan o abusan de los niños; genera o difunde información comprobablemente falsa con el propósito de perjudicar a otros; suplanta o intenta suplantar a otros; genera o difunde información de identificación personal o identificable; crea Activos que impliquen o promuevan el apoyo a una organización terrorista; crea Activos que aprueban o promueven la violencia contra las personas con base en cualquier categoría legal protegida.</p>
                <p>Además, no deberá (directa o indirectamente): (i) realizar ninguna acción que imponga o pueda imponer una carga irrazonable o desproporcionadamente grande en la infraestructura de __NOMBRE__ (o de sus proveedores externos); (ii) interferir o intentar interferir con el correcto funcionamiento del Servicio o cualquier actividad realizada en el Servicio; (iii) eludir cualquier medida que __NOMBRE__ pueda usar para evitar o restringir el acceso al Servicio (o partes del mismo); (iv) utilizar cualquier método para extraer datos de los Servicios, incluido el raspado web, la recolección web o los métodos de extracción de datos web, que no sean los permitidos a través de una API permitida; (v) ensamblar inversamente, compilar inversamente, descompilar, traducir o intentar descubrir el código fuente o los componentes subyacentes de los modelos, algoritmos y sistemas de los Servicios que no están abiertos (excepto en la medida en que tales restricciones sean contrarias a la ley aplicable) ; y (vi) reproducir, duplicar, copiar, vender, revender o explotar cualquier parte del Sitio, el uso del Sitio o el acceso al Sitio o cualquier contacto en el Sitio, sin nuestro permiso expreso por escrito.</p>

                <br/>
                <h3 className="subtitle__color_h4">Modificación de los Términos de Uso</h3>
                <p>A su exclusivo criterio, __NOMBRE__ puede modificar o reemplazar cualquiera de los Términos de uso, o cambiar, suspender o interrumpir el Servicio (incluida, entre otras, la disponibilidad de cualquier función, base de datos o contenido) en cualquier momento mediante la publicación de un aviso. en los sitios web o el Servicio de __NOMBRE__ o enviándole un correo electrónico. __NOMBRE__ también puede imponer límites a ciertas funciones y servicios o restringir su acceso a partes o la totalidad del Servicio sin previo aviso ni responsabilidad. Es su responsabilidad revisar los Términos de uso periódicamente para ver si hay cambios. Su uso continuado del Servicio después de la publicación de cualquier cambio en los Términos de uso constituye la aceptación de dichos cambios.</p>

                <br/>
                <h3 className="subtitle__color_h4">Términos de Licencia</h3>
                <p>Sujeto a su cumplimiento de este Acuerdo, las condiciones del presente y cualquier limitación aplicable a __NOMBRE__ o por ley: (i) se le otorga una licencia no exclusiva, limitada, intransferible, no sublicenciable, no asignable y libremente revocable para acceder y utilizar el Servicio para uso comercial o personal; (ii) usted posee todos los Activos que crea con los Servicios y (iii) por la presente le asignamos todos los derechos, títulos e intereses sobre dichos Activos para su uso personal o comercial. De lo contrario, __NOMBRE__ se reserva todos los derechos no otorgados expresamente en estos Términos de uso. Cada persona debe tener una cuenta única y usted es responsable de cualquier actividad realizada en su cuenta. Un incumplimiento o violación de cualquiera de nuestros Términos de uso puede resultar en la terminación inmediata de su derecho a usar nuestro Servicio.</p>

                <br/>
                <h3 className="subtitle__color_h4">Términos de Licencia</h3>
                <p>Al usar los Servicios, otorga a __NOMBRE__, sus sucesores y asigna una licencia de derechos de autor perpetua, mundial, no exclusiva, sublicenciable, sin cargo, libre de regalías e irrevocable para utilizar dichos Activos según sea necesario para proporcionar, mantener, promover y mejorar los Servicios, así como para cumplir con la ley aplicable y hacer cumplir  nuestras políticas. Usted acepta que esta licencia se proporciona sin que __NOMBRE__ le pague ninguna compensación por su envío o creación de Activos, ya que el uso de los Servicios por su parte se acepta como una compensación suficiente para la concesión de  los derechos aquí establecidos. La licencia de __NOMBREW__ sobrevive a la terminación de este Acuerdo por cualquiera de las partes, por cualquier motivo.</p>

                <br/>
                <h3 className="subtitle__color_h4">Tarfias y Pagos</h3>
                <p>Usted acepta que __NOMBRE__ le brinda acceso inmediato a un contenido digital tan pronto como complete su compra, sin esperar el período de retiro de 14 días. Por lo tanto, renuncia expresamente a su derecho a desistir de esta compra.</p>
                <p>__NOMBRE__ ofrece un servicio gratuito y de pago. Puede obtener más información sobre nuestra oferta suscripción de pago aquí. Puede suscribirse a una suscripción mensual, pagadera en euros, que se renovará automáticamente cada mes. Puede dejar de usar el Servicio y cancelar su suscripción en cualquier momento a través del sitio web o enviándonos un correo electrónico a __CONTACTO__. Si cancela su suscripción, no recibirá un reembolso ni un crédito por los montos que ya se hayan facturado o pagado. __NOMBRE__ se reserva el derecho de cambiar sus precios en cualquier momento. Si tiene un plan de suscripción, los cambios en los precios no se aplicarán hasta su próxima renovación.</p>
                <p>A menos que se indique lo contrario, sus tarifas de suscripción ("Tarifas") no incluyen impuestos, aranceles y otras evaluaciones similares federales, estatales, locales y extranjeras ("Impuestos"). Usted es responsable de todos los Impuestos asociados con su compra y es posible que le facturemos dichos Impuestos. Usted acepta pagar oportunamente dichos Impuestos y proporcionarnos la documentación que demuestre el pago o evidencia adicional que razonablemente podamos requerir. Si alguna cantidad de sus Tarifas está vencida, podemos suspender su acceso a los Servicios después de que le enviemos un aviso por escrito de pago atrasado. No puede crear más de una cuenta para beneficiarse del nivel gratuito de nuestros Servicios. Si creemos que no está utilizando el nivel Gratis de buena fe, podemos cobrarle tarifas estándar o dejar de brindarle acceso a los Servicios.</p>

                <br/>
                <h3 className="subtitle__color_h4">Terminación</h3>
                <p>__NOMBRE__ puede rescindir su acceso a la totalidad o parte del Servicio en cualquier momento si no cumple con estos Términos de uso, lo que puede resultar en la pérdida y destrucción de toda la información asociada con su cuenta. Además, cualquiera de las partes puede rescindir los Servicios por cualquier motivo y en cualquier momento mediante notificación por escrito. Si desea cancelar su cuenta, puede hacerlo siguiendo las instrucciones del Servicio. Cualquier tarifa pagada a continuación no es reembolsable. Tras cualquier rescisión, todos los derechos y licencias que se le otorgan en este Acuerdo terminarán inmediatamente, pero todas las disposiciones del presente que por su naturaleza deban sobrevivir a la rescisión sobrevivirán a la rescisión, incluidas, entre otras, las exenciones de garantía, la indemnización y las limitaciones de responsabilidad.</p>

                <br/>
                <h3 className="subtitle__color_h4">Indemnización</h3>
                <p>Deberá defender, indemnizar y eximir de toda responsabilidad a __NOMBRE__, sus afiliados y a cada uno de sus empleados, contratistas, directores, proveedores y representantes de todas las responsabilidades, pérdidas, reclamaciones y gastos, incluidos los honorarios razonables de los abogados, que surjan de o relacionado con (i) su uso o uso indebido del Servicio, o acceso a él, o (ii) su violación de los Términos de uso o cualquier ley, contrato, política, regulación u otra obligación aplicable. __NOMBRE__ se reserva el derecho de asumir la defensa y el control exclusivos de cualquier asunto sujeto a indemnización por su parte, en cuyo caso ayudará y cooperará con __NOMBRE__ en relación con el mismo.</p>

                <br/>
                <h3 className="subtitle__color_h4">Limitación de la responsabilidad</h3>
                <p>EN NINGÚN CASO __NOMBRE__ O SUS DIRECTORES, EMPLEADOS, AGENTES, SOCIOS, PROVEEDORES O PROVEEDORES DE CONTENIDO SERÁN RESPONSABLES BAJO CONTRATO, AGRAVIO, RESPONSABILIDAD ESTRICTA, NEGLIGENCIA O CUALQUIER OTRA TEORÍA LEGAL O EQUITATIVA CON RESPECTO AL SERVICIO (I) POR CUALQUIER PÉRDIDA BENEFICIOS, PÉRDIDA DE DATOS, COSTO DE ADQUISICIÓN DE BIENES O SERVICIOS SUSTITUTOS, O DAÑOS ESPECIALES, INDIRECTOS, INCIDENTALES, PUNITIVOS O CONSECUENTES DE CUALQUIER TIPO, O BIENES O SERVICIOS SUSTITUTOS, (II) POR SU CONFIANZA EN EL SERVICIO O (III) POR CUALQUIER DAÑO DIRECTO EN EXCESO (EN EL CONJUNTO) DE LAS TARIFAS PAGADAS POR USTED POR EL SERVICIO.</p>

                <br/>
                <h3 className="subtitle__color_h4">Limitación de la responsabilidad</h3>
                <p>TODO USO DEL SERVICIO Y CUALQUIER CONTENIDO SE REALIZA COMPLETAMENTE BAJO SU PROPIO RIESGO. EL SERVICIO (INCLUYENDO, SIN LIMITACIÓN, LA APLICACIÓN WEB __NOMBRE__ Y CUALQUIER CONTENIDO) SE PROPORCIONA "TAL CUAL" Y "SEGÚN DISPONIBILIDAD" Y SIN GARANTÍA DE NINGÚN TIPO, EXPRESA O IMPLÍCITA, INCLUYENDO, ENTRE OTRAS, LAS GARANTÍAS IMPLÍCITAS DE TÍTULO, NO INFRACCIÓN, COMERCIABILIDAD E IDONEIDAD PARA UN FIN EN PARTICULAR, Y CUALQUIER GARANTÍA IMPLÍCITA POR CUALQUIER CURSO DE DESEMPEÑO O USO COMERCIAL, TODAS LAS CUALES ESTÁN EXPRESAMENTE RENUNCIADAS. </p>

                <br/>
                <h3 className="subtitle__color_h4">Miscelánea</h3>
                <p>Los Términos de uso constituyen el acuerdo completo entre usted y __NOMBRE__ con respecto al Servicio, y reemplazan todas las comunicaciones y propuestas anteriores o contemporáneas (ya sean orales, escritas o electrónicas) entre usted y __NOMBRE__ con respecto al Servicio. Si se determina que alguna disposición de los Términos de uso es inaplicable o inválida, esa disposición se limitará o eliminará en la medida mínima necesaria para que los Términos de uso permanezcan en pleno vigor y efecto y exigibles. El hecho de que cualquiera de las partes no ejerza en ningún aspecto ningún derecho previsto en el presente no se considerará una renuncia a ningún otro derecho en virtud del presente. __NOMBRE__ no será responsable de ningún incumplimiento de sus obligaciones en virtud del presente debido a cualquier causa fuera del control razonable de __NOMBRE__.</p>
                <p>Los Términos de uso son personales para usted y usted no puede asignarlos ni transferirlos, excepto con el consentimiento previo por escrito de __NOMBRE__. __NOMBRE__ puede ceder, transferir o delegar cualquiera de sus derechos y obligaciones en virtud del presente sin consentimiento. No se crea ninguna agencia, sociedad, empresa conjunta o relación laboral como resultado de los Términos de uso y ninguna de las partes tiene autoridad de ningún tipo para obligar a la otra en ningún aspecto.</p>

                <br/>
                <h3 className="subtitle__color_h4">Usos Prohibidos</h3>
                <p>Usted es completamente responsable de sus actividades mientras usa el Sitio, incluido cualquier contenido, información u otros materiales que publique o cargue en el Sitio, y asume todos los riesgos asociados con el uso del Sitio. Al aceptar estos Términos, usted acepta cumplir con todas las leyes y regulaciones federales, estatales y locales aplicables en relación con su uso del Sitio. También acepta no usar el Sitio para participar en ninguna conducta prohibida o para ayudar a cualquier otra persona o entidad a participar en cualquier conducta prohibida.</p>
                <p>Nos reservamos el derecho (pero no la obligación) a nuestro exclusivo criterio de (1) monitorear el Sitio en busca de violaciones de estos Términos; (2) tomar las medidas legales apropiadas contra cualquier persona que use o acceda al Sitio de una manera que creamos que viola la ley o estos Términos, lo que incluye, entre otros, denunciar a dicho usuario a las autoridades encargadas de hacer cumplir la ley; (3) denegar el acceso al Sitio o cualquier característica del Sitio a cualquier persona que viole estos Términos o que creamos que interfiere con la capacidad de otros para disfrutar de nuestro Sitio o infringe los derechos de otros; y (4) de otro modo administrar el Sitio de una manera diseñada para proteger nuestros derechos y propiedad y para facilitar el funcionamiento adecuado del Sitio.</p>
                <p>Tiene prohibido utilizar el Sitio para la comisión de actividades dañinas o ilegales. En consecuencia, usted no puede, ni ayudar a ninguna otra persona a:</p>
                <p>Infringir estos Términos u otras políticas y términos publicados en el Sitio o aplicables de otro modo al mismo;</p>
                <p>Incluir información personal confidencial (como números de teléfono, direcciones residenciales, información de salud, números de seguro social, números de licencia de conducir u otros números de cuenta) sobre usted o cualquier otra persona en cualquier formulario web en el Sitio;</p>
                <p>Copiar o adaptar el software del Sitio, incluidos, entre otros, Flash, PHP, HTML, JavaScript u otro código;</p>
                <p>Cargar cualquier material, programa o software que contenga virus, gusanos, spyware, caballos de Troya u otro programa o código diseñado para interrumpir, destruir o limitar la funcionalidad del Sitio, lanzar un ataque de denegación de servicio o intentar de cualquier otra forma interferir con el funcionamiento y la disponibilidad del Sitio;</p>
                <p>Salvo que pueda ser el resultado del uso de un motor de búsqueda estándar o un navegador de Internet, use, inicie, desarrolle o distribuya cualquier sistema automatizado, incluidos, entre otros, cualquier araña, robot, utilidad de trampa, raspador, lector fuera de línea o cualquier extracción de datos o herramientas de extracción de recopilación de datos similares para acceder al Sitio, o usar o iniciar cualquier script u otro software no autorizado;</p>
                <p>Interferir, deshabilitar, destrozar o interrumpir el Sitio o los servidores o las redes conectadas al Sitio;</p>
                <p>Hackear, penetrar, deshabilitar o eludir las medidas de seguridad del Sitio o los servidores o redes conectados al Sitio;</p>
                <p>Hacerse pasar por otra persona o representar falsamente una afiliación con cualquier organización o institución;</p>
                <p>Enviar correo electrónico a las direcciones vinculadas o disponibles en el Sitio (incluidos estos Términos) para acosar, molestar, intimidar o amenazar a cualquiera de nuestros empleados o agentes;</p>
                <p>Intente hacer cualquiera de las anteriores.</p>

                <br/>
                <h3 className="subtitle__color_h4">Contacto</h3>
                <p>Si tiene preguntas o comentarios sobre nuestrs Términos y Condiciones de Uso, no dude en contactarnos a través de la información de contacto proporcionada en nuestro sitio web.</p>

            </div>
        </div>
    )
}

export default Terms;
